In [1]:
ls

116Cd_d,p_117Cd_bite_1_spec_factors.pkl
116Cd_d,p_117Cd_bite_2_spec_factors.pkl
116Cd_d,p_117Cd_bite_3_spec_factors.pkl
116Cd_d,t_115Cd_bite_1_spec_factors.pkl
116Cd_p,d_115Cd_bite_2_spec_factors.pkl
notebook.tex
occupancies.ipynb
Untitled.ipynb


In [67]:
import pandas as pd
import numpy as np
import glob
files = glob.glob('116Cd_d,p*')
files

['116Cd_d,p_117Cd_bite_1_spec_factors.pkl',
 '116Cd_d,p_117Cd_bite_2_spec_factors.pkl',
 '116Cd_d,p_117Cd_bite_3_spec_factors.pkl']

In [68]:
df = None
files = np.sort(glob.glob('116Cd_d,p*'))
#print(files)

df1 = pd.read_pickle(files[0])[['ENERGY']]

df2 = pd.read_pickle(files[1])[['ENERGY']]
df3 = pd.read_pickle(files[2])[['ENERGY']]

frames = [df1,df2,df3]
df = pd.concat(frames, axis = 1, sort = False)
#df = df.rename(index=str, columns={"ENERGY": "EB1"})
#df

for row in df.iterrows():
    print(np.array(row[1]))

[   0. 1222. 2183.]
[ 107.85855585 1237.         2205.        ]
[ 134.51639627 1257.         2232.        ]
[ 134.51639627 1279.         2470.5667581 ]
[ 292.23727013 1318.96957368 2482.58472949]
[ 411.0908011  1343.         2497.91397617]
[ 426.2        1355.         2569.30353722]
[ 442.6        1406.35812984 2593.83132541]
[ 498.09215467 1423.02633458 2609.22757224]
[ 522.1        1440.48778147 2621.78345166]
[ 627.29063985 1476.         2635.08961641]
[ 639.48063128 1484.32629572 2649.07558755]
[ 665.2        1648.62382511 2664.60130282]
[ 690.8        1672.43573125 2688.33946808]
[ 699.99189646 1682.51201348 2702.2653349 ]
[ 728.20495558 1691.8712204  2715.64080234]
[ 779.07887071 1743.64805937 2737.36376258]
[ 820.1        1763.40435712 2749.88008553]
[ 862.55592056 1791.79857486 2767.78117641]
[ 997.35475725 1813.10214966 2779.2       ]
[1011.99570125 1844.48746025 2813.50125923]
[1073.2        1880.88405091 2828.35972191]
[1082.46621077 1943.         2853.11473251]
[1105.246920

In [69]:
df1 = pd.read_pickle(files[0])
df2 = pd.read_pickle(files[1])
df3 = pd.read_pickle(files[2])

df2 = df2.drop([0,2,3,4,5,6,10,11])
df3 = df3.drop([0,1,2,3,4])

dp = [df1, df2, df3]



In [70]:

vacancy0, svacancy0 = 0,0
vacancy1, svacancy1 = 0,0
vacancy2, svacancy2 = 0,0
vacancy3, svacancy3 = 0,0
vacancy4, svacancy4 = 0,0
vacancy5, svacancy5 = 0,0


for f in dp:
    
    vacancy0 += np.sum(f.loc[f['L'] == 0, ['SPECTROSCOPIC_FACTOR']])
    vacancy2 += np.sum(f.loc[f['L'] == 2, ['SPECTROSCOPIC_FACTOR']])
    vacancy4 += np.sum(f.loc[f['L'] == 4, ['SPECTROSCOPIC_FACTOR']])
    vacancy5 += np.sum(f.loc[f['L'] == 5, ['SPECTROSCOPIC_FACTOR']])
    #print(vacancy0)
    
    f['ESQUARE'] = f['ERROR']**2
    
    svacancy0 += np.sqrt(np.sum(f.loc[f['L'] == 0, ['ESQUARE']]))
    svacancy2 += np.sqrt(np.sum(f.loc[f['L'] == 2, ['ESQUARE']]))
    svacancy4 += np.sqrt(np.sum(f.loc[f['L'] == 4, ['ESQUARE']]))
    svacancy5 += np.sqrt(np.sum(f.loc[f['L'] == 5, ['ESQUARE']]))

In [71]:
j = 0.5
vacancy0 = (2 * j + 1) * vacancy0
svacancy0 = (2 * j + 1) * svacancy0
print(str(vacancy0[0]) + ' +- ' + str(svacancy0[0]))

1.3058787109506043 +- 0.04197969612102154


In [72]:
j = 7/2
vacancy4 = (2 * j  + 1) * vacancy4
svacancy4 = (2 * j + 1) * svacancy4
print(str(vacancy4[0]) + ' +- ' + str(svacancy4[0]))

0.05589603013884827 +- 0.00793977700835913


In [73]:
j = 11/2
vacancy5 = (2 * j + 1) * vacancy5
svacancy5 = (2 * j + 1) * svacancy5
print(str(vacancy5[0]) + ' +- ' + str(svacancy5[0]))

5.075024858716542 +- 0.311920055218467


In [74]:
df = None
files = np.sort(glob.glob('116Cd_p,d*'))


df1 = pd.read_pickle(files[0])[['ENERGY']]

df2 = pd.read_pickle(files[1])[['ENERGY']]
df3 = pd.read_pickle(files[2])[['ENERGY']]

frames = [df1,df2,df3]
df = pd.concat(frames, axis = 1, sort = False)
#df = df.rename(index=str, columns={"ENERGY": "EB1"})
df

ENERGY       ENERGY       ENERGY
0      0.000000  1063.900000  1862.870000
1    181.000000  1085.000000  1875.200000
2    229.100000  1175.000000  2054.045985
3    343.679164  1209.564222  2077.425494
4    360.500000  1209.564222  2095.238466
5    389.000000  1248.000000  2113.200000
6    416.064688  1266.460117  2131.014162
7    472.700000  1292.473980  2131.014162
8    507.300000  1304.585912  2145.124557
9    566.068974  1317.300000  2176.865287
10   607.561258  1339.018419  2196.568275
11   645.617584  1358.300000  2220.798153
12   659.955126  1456.533866  2246.353097
13   698.316751  1471.462544  2306.889949
14   749.400000  1494.448711  2318.773859
15   776.600000  1515.596557  2332.404602
16   809.749016  1515.596557  2342.559622
17   864.244334  1538.408633  2352.409431
18   878.573382  1574.000000  2364.788262
19   901.503470  1597.000000  2374.896726
20   927.739783  1613.149085  2384.426696
21   942.557448  1625.344245  2397.177156
22   962.315664  1649.346716          NaN
23  1026.569437  1732.134407          NaN
24  1039.139722  1747.835620          NaN
25  1063.782351  1772.725731          NaN
26  1092.100000  1785.161835          NaN
27          NaN  1795.477475          NaN
28          NaN  1805.922029          NaN
29          NaN  1818.000000          NaN
30          NaN  1840.000000          NaN
31          NaN  1840.000000          NaN
32          NaN  1841.298544          NaN
33          NaN  1841.298544          NaN
34          NaN  1851.005074          NaN
35          NaN  1865.530753          NaN
36          NaN  1876.000000          NaN
37          NaN  1885.117066          NaN
38          NaN  1885.117066          NaN
39          NaN  1896.361077          NaN
40          NaN  1911.792282          NaN
41          NaN  1924.675205          NaN
42          NaN  1933.550109          NaN
43          NaN  1944.234562          NaN
44          NaN  1959.440633          NaN
45          NaN  1970.376107          NaN
46          NaN  1986.766403          NaN
47          NaN  1995.028143          NaN
48          NaN  2014.856994          NaN
49          NaN  2048.833064          NaN
50          NaN  2073.838282          NaN
51          NaN  2092.576633          NaN
52          NaN  2113.240000          NaN
53          NaN  2113.240000          NaN
54          NaN  2133.721397          NaN
55          NaN  2133.721397          NaN
56          NaN  2148.119842          NaN

In [75]:
df1 = pd.read_pickle(files[0])
df2 = pd.read_pickle(files[1])
df3 = pd.read_pickle(files[2])

df2 = df2.drop([0,1])
df3 = df3.drop([0,1,2,3,4,5,6,7,8,9])

p_d = [df1, df2, df3]

In [76]:
occupancy0, soccupancy0 = 0,0
occupancy1, soccupancy1 = 0,0
occupancy2, soccupancy2 = 0,0
occupancy3, soccupancy3 = 0,0
occupancy4, soccupancy4 = 0,0
occupancy5, soccupancy5 = 0,0


for f in p_d:
    
    occupancy0 += np.sum(f.loc[f['L'] == 0, ['SPECTROSCOPIC_FACTOR']])
    occupancy2 += np.sum(f.loc[f['L'] == 2, ['SPECTROSCOPIC_FACTOR']])
    occupancy4 += np.sum(f.loc[f['L'] == 4, ['SPECTROSCOPIC_FACTOR']])
    occupancy5 += np.sum(f.loc[f['L'] == 5, ['SPECTROSCOPIC_FACTOR']])
    
    f['ESQUARE'] = f['ERROR']**2
    
    soccupancy0 += np.sqrt(np.sum(f.loc[f['L'] == 0, ['ESQUARE']]))
    soccupancy2 += np.sqrt(np.sum(f.loc[f['L'] == 2, ['ESQUARE']]))
    soccupancy4 += np.sqrt(np.sum(f.loc[f['L'] == 4, ['ESQUARE']]))
    soccupancy5 += np.sqrt(np.sum(f.loc[f['L'] == 5, ['ESQUARE']]))

In [77]:
print(str(occupancy0[0]) + ' +- ' + str(soccupancy0[0]))

0.7791240403865303 +- 0.005609086649494438


In [78]:
print(str(occupancy4[0]) + ' +- ' + str(soccupancy4[0]))

2.728417239543084 +- 0.044663167910917304


In [79]:
print(str(occupancy5[0]) + ' +- ' + str(soccupancy5[0]))

5.123232026999504 +- 0.08132772202543714


In [80]:
print(occupancy0, vacancy0)
N0 = ((occupancy0 + vacancy0) / (1 + 1))[0]
sN0 = ((np.sqrt(soccupancy0**2 + svacancy0**2) / (1+1)))[0]
print(str(N0) + ' +- ' + str(sN0))

SPECTROSCOPIC_FACTOR    0.779124
dtype: float64 SPECTROSCOPIC_FACTOR    1.305879
dtype: float64
1.0425013756685673 +- 0.021176382714328524


In [81]:
print(occupancy4[0], vacancy4[0])
N4 = ((occupancy4 + vacancy4) / (7 + 1))[0]
sN4 = ((np.sqrt(soccupancy4**2 + svacancy4**2) / (7+1)))[0]
print(str(N4) + ' +- ' + str(sN4))

2.728417239543084 0.05589603013884827
0.34803915871024155 +- 0.005670425781496237


In [82]:
print(occupancy5[0], vacancy5[0])
N5 = ((occupancy5 + vacancy5) / (11 + 1))[0]
sN5 = ((np.sqrt(soccupancy5**2 + svacancy5**2) / (11+1)))[0]
print(str(N5) + ' +- ' + str(sN5))

5.123232026999504 5.075024858716542
0.8498547404763371 +- 0.026862344464331566


In [120]:
occ5 = occupancy5/N5
socc5 = ((occupancy5[0] * vacancy5[0]) / ((occupancy5[0] + vacancy5[0])*N5)) * np.sqrt((soccupancy5[0]/occupancy5[0])**2 + (svacancy5[0]/vacancy5[0])**2)
print(str(occ5[0]) + ' +- ' + str(socc5))

6.028362004697381 +- 0.19043180457434813


In [118]:
occ4 = occupancy4/N4
socc4 = ((occupancy4[0] * vacancy4[0]) / ((occupancy4[0] + vacancy4[0])*N4)) * np.sqrt((soccupancy4[0]/occupancy4[0])**2 + (svacancy4[0]/vacancy4[0])**2)
print(str(occ4[0]) + ' +- ' + str(socc4))

7.839397295562985 +- 0.02250286320927149


In [114]:
occ0 = occupancy0/N0
socc0 = ((occupancy0[0] * vacancy0[0]) / ((occupancy0[0] + vacancy0[0])*N0)) * np.sqrt((soccupancy0[0]/occupancy0[0])**2 + (svacancy0[0]/vacancy0[0])**2)
print(str(occ0[0]) + ' +- ' + str(socc0))

0.7473602036130357 +- 0.015420162326350226


l = 2 now

In [87]:
print(occupancy2[0], soccupancy2[0], vacancy2[0], svacancy2[0])

5.239991833742328 0.027989350133891755 0.6956830938594616 0.0058398016138457


In [88]:
N2 = (vacancy2[0] + (occupancy2[0])/(2 * 3/2 + 1))/2
sN2 = (np.sqrt(svacancy2[0]**2 + ((soccupancy2[0])/(2 * 3/2 + 1))**2))/2
print(str(N2) + ' +- ' + str(sN2))

1.002840526147522 +- 0.00455702796366294


In [121]:
occ2 = occupancy2/N2
socc2 = ((occupancy2[0] * vacancy2[0]) / ((occupancy2[0] + vacancy2[0])*N2)) * np.sqrt((soccupancy2[0]/occupancy2[0])**2 + (svacancy2[0]/vacancy2[0])**2)
print(str(occ2[0]) + ' +- ' + str(socc2))

5.225149659509776 +- 0.006093262774130948


In [92]:
totalocc = occ2 + occ0 + occ4 + occ5
totalocc

SPECTROSCOPIC_FACTOR    19.840269
dtype: float64

In [93]:
#neutron number of 116Cd
N = 116 - 48
Nfullshell = 50
#so total neutron number - the number in full shells - total occ = 0
N - Nfullshell - totalocc[0]


-1.8402691633831765

In [229]:
#missing 4 neutrons...

In [225]:
#uncertainty in normalised occupancy for l = 0
occupancy0[0]/N0 * np.sqrt((sN0/N0)**2 + (soccupancy0[0]/occupancy0[0])**2)

0.009327397432731198

In [ ]:
#this looks small